{
 "title": "Covid-19 Statistics Italy",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "2h",
 "panels": [
  {
   "title": "Deaths",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "country-overall",
     "select": [
      [
       { "params": [ "dead" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recovered",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "country-overall",
     "select": [
      [
       { "params": [ "recovered" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reported Infections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "country-overall",
     "select": [
      [
       { "params": [ "total_cases" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Infection Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 16, "w": 12, "x": 6, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "measurement": "country-cities",
     "query": "SELECT \"lat\", \"long\", \"city\", \"cases\" FROM \"country-cities\" WHERE $timeFilter GROUP BY \"city\"\n",
     "select": [
      [
       { "params": [ "lat" ], "type": "field" }
      ],
      [
       { "params": [ "long" ], "type": "field" }
      ],
      [
       { "params": [ "city" ], "type": "field" }
      ],
      [
       { "params": [ "cases" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dead & Recovered over total infected",
   "type": "graph",
   "description": "Number of recovered people over total reported cases - day by day",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "country-overall",
     "select": [
      [
       { "params": [ "recovered" ], "type": "field" },
       { "params": [ " / total_infected" ], "type": "math" }
      ],
      [
       { "params": [ "dead" ], "type": "field" },
       { "params": [ " / total_infected" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dead & Recovered through time",
   "type": "graph",
   "description": "Plot showing deaths in Italy over time using linear scale.",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "country-overall",
     "query": "SELECT \"deceduti\" FROM \"contry-overall\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "dead" ], "type": "field" },
       { "params": [ "Dead" ], "type": "alias" }
      ],
      [
       { "params": [ "recovered" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recovered over Dead",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "country-overall",
     "select": [
      [
       { "params": [ "recovered" ], "type": "field" },
       { "params": [ " / dead" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of deaths and recovered per day",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 7, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "country-overall",
     "select": [
      [
       { "params": [ "dead" ], "type": "field" },
       { "params": [ "1d" ], "type": "derivative" },
       { "params": [ "Deaths" ], "type": "alias" }
      ],
      [
       { "params": [ "recovered" ], "type": "field" },
       { "params": [ "1d" ], "type": "derivative" },
       { "params": [ "Recovered" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cases with respect to tampons",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "country-overall",
     "select": [
      [
       { "params": [ "tampons" ], "type": "field" },
       { "params": [ "Tampons" ], "type": "alias" }
      ],
      [
       { "params": [ "total_infected" ], "type": "field" },
       { "params": [ "Actual infected" ], "type": "alias" }
      ],
      [
       { "params": [ "total_cases" ], "type": "field" },
       { "params": [ "Total Infected" ], "type": "alias" }
      ],
      [
       { "params": [ "total_through_hospital" ], "type": "field" },
       { "params": [ "Cases in Hospital" ], "type": "alias" }
      ],
      [
       { "params": [ "intensive_care" ], "type": "field" },
       { "params": [ "Intensive Care" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}